name: Build and Deploy to EC2 (Production)

on:
  push:
    branches: [ main ]

env:
  VITE_API_URL: ${{ secrets.VITE_API_URL }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build \
          --build-arg VITE_API_URL=${{ env.VITE_API_URL }} \
          -t react-app:latest .
        docker save react-app:latest > react-app.tar

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ec2-user
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -i private_key -o StrictHostKeyChecking=no react-app.tar ${USER}@${HOST}:~/
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
          docker load < react-app.tar
          rm react-app.tar
          docker stop react-app || true
          docker rm react-app || true
          docker run -d --name react-app \
            -p 80:80 \
            -p 443:443 \
            -e VITE_API_URL=${{ env.VITE_API_URL }} \
            react-app:latest
        '