name: Build and Deploy to EC2 (Production)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and save Docker image (prod profile)
      run: |
        docker-compose -f docker-compose.yml --profile prod build
        docker save -o react-app-prod.tar $(docker-compose -f docker-compose.yml --profile prod config --images)

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ec2-user
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -i private_key -o StrictHostKeyChecking=no react-app-prod.tar ${USER}@${HOST}:~/
        scp -i private_key -o StrictHostKeyChecking=no docker-compose.yml ${USER}@${HOST}:~/
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
          docker load < react-app-prod.tar
          rm react-app-prod.tar
          docker-compose -f docker-compose.yml --profile prod up -d --force-recreate
        '